"""videos/<topic>/body/build_body.py -- the script for one video.

Copy this whole folder with:  python tools/new_video.py <topic>

Everything below the SHOTS list is boilerplate. Editing a video means editing
SHOTS and nothing else.

Shot kinds and the keys each one uses
-------------------------------------
  card    headline, kicker?, sub?, bullets[] or body
  number  value, kicker?, sub?
  bars    headline, data=[(label, value)], unit?, highlight=<index>?
  line    headline, data=[(label, value)], unit?, sub?
  rating  headline, data=[(label, score)], max=5
  pie     headline, data=[(label, value)]
  photo   headline, query="commons search" or file="File:Name.jpg", sub?

Every shot needs `say`: the one narration line spoken over it. One line, one
shot, one caption -- that 1:1 rule is what keeps the captions on the voice.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from studio.body import build            # noqa: E402

TOPIC = Path(__file__).resolve().parents[1].name

# --- lines for the Flow presenter (generated by hand, not by this script) ---
HOOK = "Write the 8-second hook line here."
CLOSE = "Write the 8-second sign-off here."

SHOTS = [
    {"kind": "card", "kicker": "the question", "headline": "Headline goes here",
     "bullets": ["First point.", "Second point."],
     "say": "The narration line spoken over this shot."},
]

if __name__ == "__main__":
    build(TOPIC, SHOTS)
